sudo: required
services:
  - docker

before_install:
  - docker build -t ankitt-shahh/docker-react -f Dockerfile.dev .

script:
  - docker run ankitt-shahh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react
  env: "Docker-react-env"
  bucket_name: 
  bucket_path:
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"